### DISCUSSION TITLE
How to specify description for @param.array that will appear in the openapi explorer

### DISCUSSION THREAD

**Discussion by dhurtrci** [loopbackio/loopback-next#8670] [Q&A]
In my API I have an array query parameter. I want to give it a description that can be seen in the Open API explorer.
As the array function does not have a specific argument for description, I tried putting a description in the itemSpec.

 ```
 @param.array('conditions', 'query', {
            description: 'Whatever',
            type: 'string',
            enum: Object.values(ConditionEnum)
        })
```

Unfortunately (and perhaps as one would expect), the generated openapi spec from this puts the description under the schema/items as illustrated below in the yml:
```

       - name: conditions
          in: query
          schema:
            type: array
            items:
              description: Whatever
              type: string
              enum:
                - A
                - B
                - C
```

To be visible in the API explorer, I need a way of getting the description to be at the top level - e.g.. :

```

       - name: conditions
          in: query
          description: Whatever
          schema:
            type: array
            items:
              type: string
              enum:
                - A
                - B
                - C
```
How do I accomplish this via the loopback decorators?  Is it even possible, or is the array function maybe missing a description parameter and the necessary 'wiring' to achieve this?
