### ISSUE TITLE
Modify code highlight in the docs

### ISSUE THREAD

**Issue by mbnoimi** [loopbackio/loopback-next#6873]
## Suggestion

I suggest modifying code highlight in the docs to something else. As you can see the screenshot some syntaxes are unreadable.

## Examples

![image](https://user-images.githubusercontent.com/284547/101068126-667ac880-35a9-11eb-8353-a91db433d481.png)

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dhmlau** [comment]
@mbnoimi, do you mean this page: https://loopback.io/doc/en/lb4/Controller-generator.html?
What would be your suggestion of the code highlight? Thanks.

**Comment by mbnoimi** [comment]
> do you mean this page

I mean for whole codes highlight in the docs

> What would be your suggestion of the code highlight?

I suggest using a scheme similar to [Github's color scheme](https://atom.io/themes/atom-github-theme)

**Comment by dhmlau** [comment]
@mbnoimi, it sounds good. Would you be interested to submit a PR? I believe the css files are https://github.com/strongloop/loopback.io/blob/gh-pages/css/syntax.css and/or https://github.com/strongloop/loopback.io/blob/gh-pages/css/customstyles.css.

**Comment by mbnoimi** [comment]
> Would you be interested to submit a PR? 

Unfortunately I'm still stuck to LB4 learning.

**Comment by mbnoimi** [comment]
I'm unable to read most of the snippets in the docs unless I select it to make it readable:
![image](https://user-images.githubusercontent.com/284547/101391231-149daf80-38d5-11eb-8ead-13474eb9f7c2.png)
![image](https://user-images.githubusercontent.com/284547/101391264-20897180-38d5-11eb-8e81-189f7e492acc.png)

**Comment by dougal83** [comment]
Hey @mbnoimi  Sorry to hear that you're having difficulties with the code snippets.  May I ask if you have any conditions such as colour blindness?  As a personal fix you could potentially use a browser extension such as [User CSS](https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb/related?hl=en) whereby you can alter the colours to suit you manually.

The following CSS can be used on loopback.io and as an example I've made the code background a light gray with black text.

```css
.highlight  { background: #eeeeee; border-radius: 5px; color: #000; }
.highlight .c { color: #999988; font-style: italic } /* Comment */
.highlight .err { color: #a61717; background-color: #e3d2d2 } /* Error */
.highlight .k { color: #6ab825; font-weight: bold } /* Keyword */
.highlight .o { font-weight: bold } /* Operator */
.highlight .cm { color: #999988; font-style: italic } /* Comment.Multiline */
.highlight .cp { color: #999999; font-weight: bold } /* Comment.Preproc */
.highlight .c1 { color: #999988; font-style: italic } /* Comment.Single */
.highlight .cs { color: #999999; font-weight: bold; font-style: italic } /* Comment.Special */
.highlight .gd { color: #000000; background-color: #ffdddd } /* Generic.Deleted */
.highlight .gd .x { color: #000000; background-color: #ffaaaa } /* Generic.Deleted.Specific */
.highlight .ge { font-style: italic } /* Generic.Emph */
.highlight .gr { color: #aa0000 } /* Generic.Error */
.highlight .gh { color: #999999 } /* Generic.Heading */
.highlight .gi { color: #000000; background-color: #ddffdd } /* Generic.Inserted */
.highlight .gi .x { color: #000000; background-color: #aaffaa } /* Generic.Inserted.Specific */
.highlight .go { color: #888888 } /* Generic.Output */
.highlight .gp { color: #555555 } /* Generic.Prompt */
.highlight .gs { font-weight: bold } /* Generic.Strong */
.highlight .gu { color: #aaaaaa } /* Generic.Subheading */
.highlight .gt { color: #aa0000 } /* Generic.Traceback */
.highlight .kc { color: #6ab825; font-weight: bold } /* Keyword.Constant */
.highlight .kd { color: #6ab825; font-weight: bold } /* Keyword.Declaration */
.highlight .kn { color: #6ab825; font-weight: bold } /* Keyword.Namespace */
.highlight .kp { color: #6ab825 } /* Keyword.Pseudo */
.highlight .kr { color: #6ab825; font-weight: bold } /* Keyword.Reserved */
.highlight .kt { color: #6ab825; font-weight: bold } /* Keyword.Type */
.highlight .m { color: #009999 } /* Literal.Number */
.highlight .s { color: #d14 } /* Literal.String */
.highlight .na { color: #008080 } /* Name.Attribute */
.highlight .nb { color: #0086B3 } /* Name.Builtin */
.highlight .nc { color: #445588; font-weight: bold } /* Name.Class */
.highlight .no { color: #008080 } /* Name.Constant */
.highlight .ni { color: #800080 } /* Name.Entity */
.highlight .ne { color: #990000; font-weight: bold } /* Name.Exception */
.highlight .nf { color: #990000; font-weight: bold } /* Name.Function */
.highlight .nn { color: #555555 } /* Name.Namespace */
.highlight .nt { color: #6161de } /* Name.Tag */
.highlight .nv { color: #008080 } /* Name.Variable */
.highlight .ow { font-weight: bold } /* Operator.Word */
.highlight .w { color: #bbbbbb } /* Text.Whitespace */
.highlight .mf { color: #009999 } /* Literal.Number.Float */
.highlight .mh { color: #009999 } /* Literal.Number.Hex */
.highlight .mi { color: #009999 } /* Literal.Number.Integer */
.highlight .mo { color: #009999 } /* Literal.Number.Oct */
.highlight .sb { color: #d14 } /* Literal.String.Backtick */
.highlight .sc { color: #d14 } /* Literal.String.Char */
.highlight .sd { color: #d14 } /* Literal.String.Doc */
.highlight .s2 { color: #d14 } /* Literal.String.Double */
.highlight .se { color: #d14 } /* Literal.String.Escape */
.highlight .sh { color: #d14 } /* Literal.String.Heredoc */
.highlight .si { color: #d14 } /* Literal.String.Interpol */
.highlight .sx { color: #d14 } /* Literal.String.Other */
.highlight .sr { color: #009926 } /* Literal.String.Regex */
.highlight .s1 { color: #d14 } /* Literal.String.Single */
.highlight .ss { color: #990073 } /* Literal.String.Symbol */
.highlight .bp { color: #999999 } /* Name.Builtin.Pseudo */
.highlight .vc { color: #008080 } /* Name.Variable.Class */
.highlight .vg { color: #008080 } /* Name.Variable.Global */
.highlight .vi { color: #008080 } /* Name.Variable.Instance */
.highlight .il { color: #009999 } /* Literal.Number.Integer.Long */
```
